// Copyright 2022 The SiliFuzz Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by ucontext_offsets_gen.cc, do not change
#ifndef THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
#define THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
#define UCONTEXT_FPREGS_OFFSET 0x0
#define UCONTEXT_GREGS_R8_OFFSET 0x200
#define UCONTEXT_GREGS_R9_OFFSET 0x208
#define UCONTEXT_GREGS_R10_OFFSET 0x210
#define UCONTEXT_GREGS_R11_OFFSET 0x218
#define UCONTEXT_GREGS_R12_OFFSET 0x220
#define UCONTEXT_GREGS_R13_OFFSET 0x228
#define UCONTEXT_GREGS_R14_OFFSET 0x230
#define UCONTEXT_GREGS_R15_OFFSET 0x238
#define UCONTEXT_GREGS_RAX_OFFSET 0x268
#define UCONTEXT_GREGS_RBX_OFFSET 0x258
#define UCONTEXT_GREGS_RCX_OFFSET 0x270
#define UCONTEXT_GREGS_RDX_OFFSET 0x260
#define UCONTEXT_GREGS_RBP_OFFSET 0x250
#define UCONTEXT_GREGS_RSP_OFFSET 0x278
#define UCONTEXT_GREGS_RSI_OFFSET 0x248
#define UCONTEXT_GREGS_RDI_OFFSET 0x240
#define UCONTEXT_GREGS_RIP_OFFSET 0x280
#define UCONTEXT_GREGS_EFLAGS_OFFSET 0x288
#define UCONTEXT_GREGS_FS_BASE_OFFSET 0x2a0
#define UCONTEXT_GREGS_GS_BASE_OFFSET 0x2a8
#define UCONTEXT_GREGS_CS_OFFSET 0x290
#define UCONTEXT_GREGS_SS_OFFSET 0x296
#define UCONTEXT_GREGS_FS_OFFSET 0x294
#define UCONTEXT_GREGS_GS_OFFSET 0x292
#define UCONTEXT_GREGS_ES_OFFSET 0x29a
#define UCONTEXT_GREGS_DS_OFFSET 0x298
#endif  // THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
