// Copyright 2024 The SiliFuzz Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by ucontext_offsets_gen.cc, do not change
#ifndef THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
#define THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
#define UCONTEXT_FPREGS_OFFSET 0x0
#define UCONTEXT_GREGS_OFFSET 0x200
#define GREGS_R8_OFFSET 0x0
#define GREGS_R9_OFFSET 0x8
#define GREGS_R10_OFFSET 0x10
#define GREGS_R11_OFFSET 0x18
#define GREGS_R12_OFFSET 0x20
#define GREGS_R13_OFFSET 0x28
#define GREGS_R14_OFFSET 0x30
#define GREGS_R15_OFFSET 0x38
#define GREGS_RAX_OFFSET 0x68
#define GREGS_RBX_OFFSET 0x58
#define GREGS_RCX_OFFSET 0x70
#define GREGS_RDX_OFFSET 0x60
#define GREGS_RBP_OFFSET 0x50
#define GREGS_RSP_OFFSET 0x78
#define GREGS_RSI_OFFSET 0x48
#define GREGS_RDI_OFFSET 0x40
#define GREGS_RIP_OFFSET 0x80
#define GREGS_EFLAGS_OFFSET 0x88
#define GREGS_FS_BASE_OFFSET 0xa0
#define GREGS_GS_BASE_OFFSET 0xa8
#define GREGS_CS_OFFSET 0x90
#define GREGS_SS_OFFSET 0x96
#define GREGS_FS_OFFSET 0x94
#define GREGS_GS_OFFSET 0x92
#define GREGS_ES_OFFSET 0x9a
#define GREGS_DS_OFFSET 0x98
#endif  // THIRD_PARTY_SILIFUZZ_UTIL_UCONTEXT_X86_64_UCONTEXT_OFFSETS_H_
