.TH LIBPFM 3  "November, 2023" "" "Linux Programmer's Manual"
.SH NAME
libpfm_intel_icx_unc_m3upi - support for Intel IcelakeX Server M3UPI uncore PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: icx_unc_m3upi[0-3]
.B PMU desc: Intel IcelakeX M3UPI uncore PMU
.sp
.SH DESCRIPTION
The library supports the Intel IcelakeX M3UPI (Mesh to UPI) uncore PMU.
Each M3UPI PMU implements 4 generic counters.

.SH MODIFIERS
The following modifiers are supported on Intel IcelakeX M3UPI uncore PMU:
.TP
.B e
Enable edge detection, i.e., count only when there is a state transition from no occurrence of the event to at least one occurrence. This modifier must be combined with a threshold modifier (t) with a value greater or equal to one.  This is a boolean modifier.
.TP
.B t
Set the threshold value. When set to a non-zero value, the counter counts the number
of IRP clockticks in which the number of occurrences of the event is greater or equal to
the threshold.  This is an integer modifier with values in the range [0:255].
.B i
Invert the threshold (t) test from strictly greater than to less or equal to. This is a boolean modifier.
.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
