.TH LIBPFM 3  "January, 2024" "" "Linux Programmer's Manual"
.SH NAME
libpfm_intel_spr_unc_cha - support for Intel IcelakeX Server CHA uncore PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: spr_unc_cha[0-59]
.B PMU desc: Intel SapphireRapids CHA uncore PMU
.sp
.SH DESCRIPTION
The library supports the Intel SapphireRapids CHA (coherency and home agent) uncore PMU.
There is one CHA-box PMU per physical core. Therefore there are up forty identical CHA
PMU instances numbered from 0 up to possibly 59. On dual-socket systems, the number refers to the CHA
PMUs on the socket where the program runs.

Each CHA PMU implements 4 generic counters.

.SH MODIFIERS
The following modifiers are supported on Intel SapphireRapids CHA uncore PMU:
.TP
.B e
Enable edge detection, i.e., count only when there is a state transition from no occurrence of the event to at least one occurrence. This modifier must be combined with a threshold modifier (t) with a value greater or equal to one.  This is a boolean modifier.
.TP
.B t
Set the threshold value. When set to a non-zero value, the counter counts the number
of CHA clockticks in which the number of occurrences of the event is greater or equal to
the threshold.  This is an integer modifier with values in the range [0:255].
.TP
.B i
Invert the threshold (t) test from strictly greater than to less or equal to. This is a boolean modifier.

.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
