.TH LIBPFM 3  "August, 2012" "" "Linux Programmer's Manual"
.SH NAME
libpfm_intel_snbep_unc_imc - support for Intel Sandy Bridge-EP Integrated Memory Controller (IMC)  uncore PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: snbep_unc_imc[0-3]
.B PMU desc: Intel Sandy Bridge-EP IMC uncore PMU
.sp
.SH DESCRIPTION
The library supports the Intel Sandy Bridge Integrated Memory Controller (IMC) uncore PMU.
This PMU model only exists on Sandy Bridge model 45. There are four IMC PMUs per socket.

.SH MODIFIERS
The following modifiers are supported on Intel Sandy Bridge C-Box uncore PMU:
.TP
.B i
Invert the meaning of the event. The counter will now count IMC cycles in which the
event is \fBnot\fR occurring. This is a boolean modifier
.TP
.B e
Enable edge detection, i.e., count only when there is a state transition from no occurrence of the event to at least one occurrence. This modifier must be combined with a threshold modifier (t) with a value greater or equal to one.  This is a boolean modifier.
.TP
.B t
Set the threshold value. When set to a non-zero value, the counter counts the number
of IMC cycles in which the number of occurrences of the event is greater or equal to
the threshold.  This is an integer modifier with values in the range [0:255].

.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
