.TH LIBPFM 3  "August, 2012" "" "Linux Programmer's Manual"
.SH NAME
libpfm_arm_ac8 - support for ARM Cortex A8 PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: arm_ac8
.B PMU desc: ARM Cortex A8
.sp
.SH DESCRIPTION
The library supports the ARM Cortex A8 core PMU.

This PMU supports 2 counters and has no privilege levels filtering.
No event modifiers are available.

.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
