.TH LIBPFM 3  "March, 2021" "" "Linux Programmer's Manual"
.SH NAME
libpfm_amd64_fam19h_zen3_l3 - support for AMD64 Family 19h L3 PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: amd64_fam19h_zen3_l3
.B PMU desc: AMD64 Fam19h Zen3 L3
.sp
.SH DESCRIPTION
The library supports AMD Family 19h processors Zen3 L3 PMU in both 32 and 64-bit modes.

At this point, there is no modifier supported.
.SH AUTHORS
.nf
Stephane Eranian
.if
.PP
