.TH LIBPFM 3  "September, 2009" "" "Linux Programmer's Manual"
.SH NAME
libpfm_intel_core - support for Intel Core-based processors
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: core
.B PMU desc: Intel Core
.sp
.SH DESCRIPTION
The library supports all Intel Core-based processors that includes models 15, 23, 29.

.SH MODIFIERS
The following modifiers are supported on Intel Core processors:
.TP
.B u
Measure at user level which includes privilege levels 1, 2, 3. This corresponds to \fBPFM_PLM3\fR.
This is a boolean modifier.
.TP
.B k
Measure at kernel level which includes privilege level 0. This corresponds to \fBPFM_PLM0\fR.
This is a boolean modifier.
.TP
.B i
Invert the meaning of the event. The counter will now count cycles in which the event is \fBnot\fR
occurring. This is a boolean modifier
.TP
.B e
Enable edge detection, i.e., count only when there is a state transition from no occurrence of the event
to at least one occurrence. This modifier must be combined with a counter mask modifier (m) with a value greater or equal to one.
This is a boolean modifier.
.TP
.B c
Set the counter mask value. The mask acts as a threshold. The counter will count the number of cycles
in which the number of occurrences of the event is greater or equal to the threshold. This is an integer
modifier with values in the range [0:255].

.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
