.TH LIBPFM 3  "November, 2013" "" "Linux Programmer's Manual"
.SH NAME
libpfm_intel_rapl - support for Intel RAPL PMU
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: rapl
.B PMU desc: Intel RAPL (Intel SandyBridge, IvyBridge, Haswell)
.sp
.SH DESCRIPTION
The library supports the Intel Running Average Power Limit (RAPL)
energy consumption counters. This is a socket-level set of counters
which reports energy consumption in Joules. There are up to 3 counters
each measuring only one event. The following events are defined:
.TP
.B  RAPL_ENERGY_CORES
On all processors, the event reports the number of Joules consumed by all cores.
 On all processors,
.TP
.B RAPL_ENERGYC_PKG
On all processors, th event reports the number of Joules consumed by all
the cores and Last Level cache (L3).
.TP
.B RAPL_ENERGY_DRAM
On server processors, the event reports the number of Joules consumed
n by the DRAM controller.

By construction, the events are socket-level and can only be measured in
system-wide mode. It is necessary and sufficient to measure only one CPU
per socket to get meaningful results.

.SH MODIFIERS
The PMU does not support any modifiers.
.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
