.TH LIBPFM 3  "September, 2009" "" "Linux Programmer's Manual"
.SH NAME
 libpfm_intel_p6 - support for Intel P5 based processors
.SH SYNOPSIS
.nf
.B #include <perfmon/pfmlib.h>
.sp
.B PMU name: pm, ppro, pii, piii, p6
.B PMU desc: Intel Pentium M, Intel Pentium Pro, Intel Pentium II, Intel Pentium III, Intel P6
.sp
.SH DESCRIPTION
The library supports all Intel P6-based processors all the way back to the Pentium Pro. Although
all those processors offers the same PMU architecture, they differ in the events they provide.

.SH MODIFIERS
The following modifiers are supported on all Intel P6 processors:
.TP
.B u
Measure at user level which includes privilege levels 1, 2, 3. This corresponds to \fBPFM_PLM3\fR.
This is a boolean modifier.
.TP
.B k
Measure at kernel level which includes privilege level 0. This corresponds to \fBPFM_PLM0\fR.
This is a boolean modifier.
.TP
.B i
Invert the meaning of the event. The counter will now count cycles in which the event is \fBnot\fR
occurring. This is a boolean modifier
.TP
.B e
Enable edge detection, i.e., count only when there is a state transition. This is a boolean modifier.
.TP
.B c
Set the counter mask value. The mask acts as a threshold. The counter will count the number of cycles
in which the number of occurrences of the event is greater or equal to the threshold. This is an integer
modifier with values in the range [0:255].
.SH AUTHORS
.nf
Stephane Eranian <eranian@gmail.com>
.if
.PP
